baseURL = "https://cloudprober.github.io/"
languageCode = "en-us"
title = "Cloudprober"
theme = "hugo-material-docs"
googleAnalytics = "UA-79661-8"

[params]
  provider = "GitHub"
  repo_url = "https://github.com/google/cloudprober"
  
[[menu.main]]
  name   = "Overview"
  url    = "/"
  weight = 1

[[menu.main]]
  name   = "Getting started"
  url    = "getting-started/"
  weight = 10

[[menu.main]]
  name   = "What is a Probe"
  url    = "probe/"
  weight = 20
